# Generated by Django 4.2.10 on 2024-08-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='value',
        ),
        migrations.AddField(
            model_name='balance',
            name='bonus_count',
            field=models.PositiveIntegerField(default=1000, editable=False, verbose_name='Текущее количество бонусов'),
        ),
    ]
