# Generated by Django 4.2.10 on 2024-08-18 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='groups_of_courses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
